apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-cache-deployment
spec:
  selector:
    matchLabels:
      app: distributed-cache
  replicas: 2
  template:
    metadata:
      labels:
        app: distributed-cache
    spec:
      containers:
        - name: distributed-cache
          image: swaminathanmuthuveerappan/lru_cache_load_balancer:1.0
          env:
            - name: CACHE_SERVERS
              value: "http://cache-0.cache.default.svc.cluster.local:8080 http://cache-1.cache.default.svc.cluster.local:8080 http://cache-2.cache.default.svc.cluster.local:8080"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-cache-service
spec:
  type: NodePort
  selector:
    app: distributed-cache
  ports:
    - port: 8081
      nodePort: 32222